#pragma once

static const char ONBOARD_HTML[] =
"<!DOCTYPE html><html><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MimiClaw Setup</title>"
"<style>"
":root{--bg:#0f1115;--panel:#171a21;--line:#2a2f3a;--text:#e8eaf0;--muted:#8b93a3;"
"--accent:#f6a821;--accent-dim:#f6a82122;--ok:#4cc38a;--err:#e5484d}"
"@media(prefers-color-scheme:light){:root{--bg:#f4f5f7;--panel:#fff;--line:#e2e4e9;"
"--text:#1c2027;--muted:#6b7280;--accent:#c77d00;--accent-dim:#c77d0014}}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,'Segoe UI',Roboto,sans-serif;background:var(--bg);"
"color:var(--text);padding:20px 16px 40px;max-width:460px;margin:0 auto;line-height:1.45}"
"header{margin:8px 0 20px}"
"h1{font-size:1.25em;font-weight:700;letter-spacing:-.01em}"
"h1 b{color:var(--accent)}"
".addr{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.78em;color:var(--muted);margin-top:4px}"
".addr a{color:var(--accent);text-decoration:none}"
".card{background:var(--panel);border:1px solid var(--line);border-radius:10px;margin:10px 0;overflow:hidden}"
".card-hdr{display:flex;justify-content:space-between;align-items:center;padding:13px 16px;"
"cursor:pointer;user-select:none;font-size:.8em;font-weight:600;letter-spacing:.08em;"
"text-transform:uppercase;color:var(--muted)}"
".card:not(.collapsed) .card-hdr{color:var(--text)}"
".card-hdr::after{content:'\\25BE';color:var(--muted);transition:transform .15s}"
".card.collapsed .card-hdr::after{transform:rotate(-90deg)}"
".card.collapsed .card-body{display:none}"
".card-body{padding:2px 16px 16px}"
"label{display:block;margin:12px 0 5px;font-size:.78em;color:var(--muted)}"
"input,select{width:100%;padding:10px 12px;border:1px solid var(--line);border-radius:8px;"
"font-size:.95em;outline:none;background:var(--bg);color:var(--text);appearance:none}"
"input:focus,select:focus{border-color:var(--accent)}"
"input::placeholder{color:var(--muted);opacity:.6}"
".btn{display:block;width:100%;padding:12px;border:none;border-radius:8px;font-size:.95em;"
"font-weight:600;cursor:pointer;margin:10px 0 4px}"
".btn-scan{background:var(--accent-dim);color:var(--accent)}"
".btn-save{background:var(--accent);color:#14161b;margin-top:22px;padding:14px;font-size:1em}"
".btn:active{opacity:.75}"
".btn:disabled{opacity:.5;cursor:default}"
".ap-list{max-height:210px;overflow-y:auto;border:1px solid var(--line);border-radius:8px;margin:4px 0 8px}"
".ap-item{padding:10px 12px;border-bottom:1px solid var(--line);cursor:pointer;"
"display:flex;justify-content:space-between;align-items:center;font-size:.92em}"
".ap-item:last-child{border-bottom:none}"
".ap-item:active{background:var(--accent-dim)}"
".ap-rssi{color:var(--muted);font-size:.8em;font-family:ui-monospace,Menlo,Consolas,monospace}"
".ap-lock::before{content:'\\1F512';font-size:.72em;margin-right:5px}"
".status{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);max-width:90%;"
"background:var(--panel);border:1px solid var(--line);color:var(--text);padding:11px 18px;"
"border-radius:99px;font-size:.9em;box-shadow:0 4px 16px rgba(0,0,0,.35);display:none;white-space:nowrap}"
".status.ok{border-color:var(--ok);color:var(--ok)}"
".status.err{border-color:var(--err);color:var(--err)}"
"</style></head><body>"

"<header>"
"<h1><b>Mimi</b>Claw Setup</h1>"
"<div class='addr' id='addr'>Portal: <a href='http://192.168.4.1'>192.168.4.1</a> (hotspot)</div>"
"</header>"

/* WiFi section (expanded by default) */
"<div class='card' id='sec-wifi'>"
"<div class='card-hdr' onclick='toggle(this)'>WiFi</div>"
"<div class='card-body'>"
"<button class='btn btn-scan' onclick='scan()'>Scan networks</button>"
"<div class='ap-list' id='ap-list' style='display:none'></div>"
"<label>SSID</label>"
"<input id='ssid' placeholder='WiFi network name'>"
"<label>Password</label>"
"<input id='password' type='password' placeholder='WiFi password'>"
"</div></div>"

/* LLM section */
"<div class='card collapsed' id='sec-llm'>"
"<div class='card-hdr' onclick='toggle(this)'>LLM</div>"
"<div class='card-body'>"
"<label>API Key</label>"
"<input id='api_key' type='password' placeholder='sk-...'>"
"<label>Model</label>"
"<input id='model' placeholder='claude-opus-4-5' value='claude-opus-4-5'>"
"<label>Provider</label>"
"<select id='provider'>"
"<option value='anthropic'>Anthropic</option>"
"<option value='openai'>OpenAI</option>"
"</select>"
"</div></div>"

/* Telegram section */
"<div class='card collapsed' id='sec-tg'>"
"<div class='card-hdr' onclick='toggle(this)'>Telegram</div>"
"<div class='card-body'>"
"<label>Bot Token</label>"
"<input id='tg_token' placeholder='123456:ABC-DEF...'>"
"</div></div>"

/* Feishu section */
"<div class='card collapsed' id='sec-feishu'>"
"<div class='card-hdr' onclick='toggle(this)'>Feishu</div>"
"<div class='card-body'>"
"<label>App ID</label>"
"<input id='feishu_app_id' placeholder='cli_xxxx'>"
"<label>App Secret</label>"
"<input id='feishu_app_secret' type='password' placeholder='App Secret'>"
"</div></div>"

/* Proxy section */
"<div class='card collapsed' id='sec-proxy'>"
"<div class='card-hdr' onclick='toggle(this)'>Proxy</div>"
"<div class='card-body'>"
"<label>Host</label>"
"<input id='proxy_host' placeholder='192.168.1.100'>"
"<label>Port</label>"
"<input id='proxy_port' type='number' placeholder='7890'>"
"<label>Type</label>"
"<select id='proxy_type'>"
"<option value=''>None</option>"
"<option value='http'>HTTP</option>"
"<option value='socks5'>SOCKS5</option>"
"</select>"
"</div></div>"

/* Search section */
"<div class='card collapsed' id='sec-search'>"
"<div class='card-hdr' onclick='toggle(this)'>Search</div>"
"<div class='card-body'>"
"<label>Brave Search API Key</label>"
"<input id='search_key' type='password' placeholder='BSA...'>"
"<label>Tavily API Key</label>"
"<input id='tavily_key' type='password' placeholder='tvly-...'>"
"</div></div>"

"<button class='btn btn-save' id='save-btn' onclick='save()'>Save &amp; Restart</button>"
"<div class='status' id='status'></div>"

"<script>"
"function toggle(el){"
"el.parentElement.classList.toggle('collapsed')}"

"function toast(msg,cls){"
"var s=document.getElementById('status');"
"s.textContent=msg;s.className='status '+(cls||'');s.style.display='block'}"

"function loadConfig(){"
"fetch('/config').then(r=>r.json()).then(cfg=>{"
"Object.keys(cfg).forEach(k=>{"
"var el=document.getElementById(k);"
"if(el && cfg[k] !== undefined && cfg[k] !== null){el.value=cfg[k]}"
"});"
"if(cfg.sta_ip && cfg.sta_ip!=='0.0.0.0'){"
"document.getElementById('addr').innerHTML="
"'Portal: <a href=\"http://'+cfg.sta_ip+'\">'+cfg.sta_ip+'</a> (your WiFi) &middot; "
"<a href=\"http://192.168.4.1\">192.168.4.1</a> (hotspot)'}"
"}).catch(()=>{})}"

"function scan(){"
"var btn=event.target;btn.textContent='Scanning...';btn.disabled=true;"
"fetch('/scan').then(r=>r.json()).then(list=>{"
"var el=document.getElementById('ap-list');el.style.display='block';el.innerHTML='';"
"list.forEach(ap=>{"
"var d=document.createElement('div');d.className='ap-item';"
"d.innerHTML='<span>'+(ap.auth?'<span class=ap-lock></span>':'')+ap.ssid+'</span><span class=ap-rssi>'+ap.rssi+' dBm</span>';"
"d.onclick=function(){document.getElementById('ssid').value=ap.ssid};"
"el.appendChild(d)});"
"btn.textContent='Scan networks';btn.disabled=false;"
"}).catch(()=>{toast('Scan failed','err');btn.textContent='Scan networks';btn.disabled=false})}"

"function save(){"
"var fields=['ssid','password','api_key','model','provider','tg_token',"
"'feishu_app_id','feishu_app_secret','proxy_host','proxy_port','proxy_type','search_key','tavily_key'];"
"var data={};"
"fields.forEach(f=>{data[f]=document.getElementById(f).value.trim()});"
"var btn=document.getElementById('save-btn');btn.disabled=true;"
"toast('Saving...');"
"fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})"
".then(r=>{if(!r.ok)throw 0;toast('Saved. Device restarting...','ok')})"
".catch(()=>{toast('Save failed. Try again.','err');btn.disabled=false})}"
"loadConfig();"
"</script>"
"</body></html>";
